In [1]:
import torch

In [3]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

In [4]:
c = a * b

In [5]:
c

tensor(6., grad_fn=<MulBackward0>)

In [6]:
print(a), print(b)

tensor(2., requires_grad=True)
tensor(3., requires_grad=True)


(None, None)

In [7]:
def c_hook(grad):
    print(grad)
    return grad + 2

In [8]:
c.register_hook(c_hook)

In [9]:
c.register_hook(lambda grad : print(grad))

In [10]:
c.retain_grad() # save the gradients on the forward and backward graph on intermediate nodes

In [ ]:
c.backward()

In [ ]:
d = torch.tensor(4.0, requires_grad=True)

In [ ]:
d.register_hook(lambda grad: grad + 100)

In [ ]:
e = c * d

In [ ]:
e

In [ ]:
e.retain_grad()

In [ ]:
e.register_hook(lambda grad: grad * 2)

In [ ]:
import torch.nn as nn

In [ ]:
class MyMultiply(nn.Module):
    def __init__(self):
        super(MyMultiply, self).__init__()
    @staticmethod
    def forward(a, b):
        return a * b

In [ ]:
def backward_hook(module, grad_input, grad_output):
    print('module:', module)
    print('grad_input', grad_input)
    print('grad_output', grad_output)

In [ ]:
my_multiply = MyMultiply()

In [ ]:
my_multiply.register_full_backward_hook(backward_hook)

In [ ]:
c = my_multiply(a, b)
c.backward()

In [ ]:
from transformers import AutoTokenizer, AutoModelForMaskedLM

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('roberta-base')
model = AutoModelForMaskedLM.from_pretrained('roberta-base')

In [ ]:
sentence = "A pleasure to watch. <mask> <mask> great."

In [ ]:
token_ids = tokenizer.encode(sentence, return_tensors="pt")
token_ids

In [ ]:
masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().flatten()

In [ ]:
masked_position

In [ ]:
model(token_ids)

In [ ]:
with torch.no_grad():
    output = model(token_ids)

In [ ]:
output

In [ ]:
last_hidden_state = output[0].squeeze()

In [ ]:
last_hidden_state

In [ ]:
list_of_list = []
for index, mask_index in enumerate(masked_position):
    print(f"index: {index}, mask_index: {mask_index}")
    mask_hidden_state = last_hidden_state[mask_index]
    idx = torch.topk(mask_hidden_state, k = 5, dim=0)[1]
    print(f"idx: {idx}")
    words = [tokenizer.decode(x.item()).strip() for x in idx]
    list_of_list.append(words)
    print(f"Mask: {index+1}, Guesses: {words}")

In [ ]:
best_guess = ""
for j in list_of_list:
    best_guess = best_guess+" "+j[0]

In [ ]:
best_guess

In [ ]:
from datasets import load_dataset

In [ ]:
sst2 = load_dataset("glue","sst2")

In [ ]:
k_16_val = sst2['validation'][:16]

In [ ]:
k_16_val

In [2]:
input_ids = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
input_ids

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
trigger_token_pos = torch.tensor([[2],[1],[0]])

In [5]:
trigger_token_pos

tensor([[2],
        [1],
        [0]])

In [10]:
input_ids

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
input_ids = torch.tensor([1,2,3])

In [18]:
input_ids[1] = 9

In [33]:
input_ids

tensor([1, 9, 3])

In [41]:
import numpy as np
input_ids2 = np.array([4,5,6])
input_ids3 = np.array([1,2,3])

In [ ]:
encoding_list = []
encoding_list.append(input_ids2)
encoding_list.append(input_ids3)
np.array(encoding_list)

In [35]:
input_ids0 = torch.stack((input_ids, input_ids2), dim=0)

In [39]:
encoding_list = 

[array([1, 9, 3]), array([4, 5, 6])]

In [36]:
torch.stack((input_ids0, input_ids2), dim=0)

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [3] at entry 1