In [1]:
import torch

In [2]:
trigger_token_pos = torch.tensor([[1,2],[0,1],[1,2]])

In [3]:
trigger_token_pos.T

tensor([[1, 0, 1],
        [2, 1, 2]])

In [4]:
x = torch.randn(3, 6, 4)
x

tensor([[[ 0.6082,  0.0482, -0.2665,  0.7163],
         [-0.8828, -0.5433, -1.1450, -0.8959],
         [ 0.9547, -0.7531,  1.1753,  0.2581],
         [ 0.1851,  0.2280, -1.3549, -0.4954],
         [ 0.0437,  1.5645, -1.5307, -0.2295],
         [ 0.1934, -1.1823,  0.5534,  0.6590]],

        [[ 0.4818,  0.5660,  0.0623, -1.4567],
         [ 0.3057,  0.1353, -0.0684,  0.3893],
         [ 0.6361, -1.6550,  0.5611, -1.1687],
         [ 0.2272, -0.2326,  1.3579,  0.5317],
         [-1.2789,  0.9225, -0.0173, -0.3347],
         [ 1.2252,  0.3830, -0.1981, -1.3286]],

        [[-0.3577, -1.1320, -0.8501, -0.4215],
         [ 0.6297, -0.3022, -1.5256, -1.3328],
         [ 0.9218,  0.8594, -1.7160, -0.7785],
         [-1.3547, -1.5040, -0.6657,  0.7324],
         [-0.7868, -0.7438,  0.4914,  1.1342],
         [ 0.0533, -0.2324,  1.2454,  0.1514]]])

In [5]:
mask = torch.where(x >= 0.5, True, False)

In [6]:
mask

tensor([[[ True, False, False,  True],
         [False, False, False, False],
         [ True, False,  True, False],
         [False, False, False, False],
         [False,  True, False, False],
         [False, False,  True,  True]],

        [[False,  True, False, False],
         [False, False, False, False],
         [ True, False,  True, False],
         [False, False,  True,  True],
         [False,  True, False, False],
         [ True, False, False, False]],

        [[False, False, False, False],
         [ True, False, False, False],
         [ True,  True, False, False],
         [False, False, False,  True],
         [False, False, False,  True],
         [False, False,  True, False]]])

In [11]:
idx = torch.where(mask)

In [14]:
idx

(tensor([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 tensor([0, 0, 2, 2, 4, 5, 5, 0, 2, 2, 3, 3, 4, 5, 1, 2, 2, 3, 4, 5]),
 tensor([0, 3, 0, 2, 1, 2, 3, 1, 0, 2, 2, 3, 1, 0, 0, 0, 1, 3, 3, 2]))

In [12]:
x[idx] = 1

In [13]:
x

tensor([[[ 1.0000,  0.0482, -0.2665,  1.0000],
         [-0.8828, -0.5433, -1.1450, -0.8959],
         [ 1.0000, -0.7531,  1.0000,  0.2581],
         [ 0.1851,  0.2280, -1.3549, -0.4954],
         [ 0.0437,  1.0000, -1.5307, -0.2295],
         [ 0.1934, -1.1823,  1.0000,  1.0000]],

        [[ 0.4818,  1.0000,  0.0623, -1.4567],
         [ 0.3057,  0.1353, -0.0684,  0.3893],
         [ 1.0000, -1.6550,  1.0000, -1.1687],
         [ 0.2272, -0.2326,  1.0000,  1.0000],
         [-1.2789,  1.0000, -0.0173, -0.3347],
         [ 1.0000,  0.3830, -0.1981, -1.3286]],

        [[-0.3577, -1.1320, -0.8501, -0.4215],
         [ 1.0000, -0.3022, -1.5256, -1.3328],
         [ 1.0000,  1.0000, -1.7160, -0.7785],
         [-1.3547, -1.5040, -0.6657,  1.0000],
         [-0.7868, -0.7438,  0.4914,  1.0000],
         [ 0.0533, -0.2324,  1.0000,  0.1514]]])

In [39]:
x = torch.where(mask, x, 0)

In [40]:
x

tensor([[[0.0000, 0.0000, 0.5961, 0.6417],
         [0.0000, 0.0000, 0.0000, 0.9650],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 1.0377, 0.0000, 0.6249],
         [0.0000, 0.7296, 1.1157, 0.9925]],

        [[0.0000, 0.0000, 2.1002, 0.0000],
         [0.6385, 0.0000, 0.0000, 1.0412],
         [0.0000, 0.0000, 0.0000, 0.8569],
         [2.0166, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 2.3255, 0.0000],
         [0.0000, 0.0000, 0.8258, 0.0000]],

        [[0.0000, 0.0000, 0.5408, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.9703, 1.7572],
         [0.0000, 0.0000, 0.0000, 0.7077],
         [0.0000, 1.2429, 1.0553, 0.0000],
         [0.5061, 0.0000, 2.2727, 0.0000]]])

In [30]:
mask = x.ge(0.5)

In [32]:
torch.masked_select(x,mask)

tensor([0.5961, 0.6417, 0.9650, 1.0377, 0.6249, 0.7296, 1.1157, 0.9925, 2.1002,
        0.6385, 1.0412, 0.8569, 2.0166, 2.3255, 0.8258, 0.5408, 0.9703, 1.7572,
        0.7077, 1.2429, 1.0553, 0.5061, 2.2727])

In [28]:
l = []
for tok_pos in trigger_token_pos.T:
    l.append(x[torch.arange(x.size(0)), tok_pos])
l

[tensor([[-0.6948, -0.1627, -0.0806,  0.9650],
         [-0.3522, -2.5227,  2.1002, -0.6313],
         [-0.6079, -1.0182, -0.0453, -0.8593]]),
 tensor([[-0.8798, -1.2421,  0.4829, -0.6940],
         [ 0.6385, -1.3077, -0.2839,  1.0412],
         [ 0.3191,  0.2043,  0.9703,  1.7572]])]

In [24]:
x[torch.arange(x.size(0)), torch.tensor([1,0,2])]

tensor([[-0.6948, -0.1627, -0.0806,  0.9650],
        [-0.3522, -2.5227,  2.1002, -0.6313],
        [ 0.3191,  0.2043,  0.9703,  1.7572]])

In [3]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

In [4]:
c = a * b

In [5]:
c

tensor(6., grad_fn=<MulBackward0>)

In [6]:
print(a), print(b)

tensor(2., requires_grad=True)
tensor(3., requires_grad=True)


(None, None)

In [7]:
def c_hook(grad):
    print(grad)
    return grad + 2

In [8]:
c.register_hook(c_hook)

In [9]:
c.register_hook(lambda grad : print(grad))

In [10]:
c.retain_grad() # save the gradients on the forward and backward graph on intermediate nodes

In [ ]:
c.backward()

In [ ]:
d = torch.tensor(4.0, requires_grad=True)

In [ ]:
d.register_hook(lambda grad: grad + 100)

In [ ]:
e = c * d

In [ ]:
e

In [ ]:
e.retain_grad()

In [ ]:
e.register_hook(lambda grad: grad * 2)

In [ ]:
import torch.nn as nn

In [ ]:
class MyMultiply(nn.Module):
    def __init__(self):
        super(MyMultiply, self).__init__()
    @staticmethod
    def forward(a, b):
        return a * b

In [ ]:
def backward_hook(module, grad_input, grad_output):
    print('module:', module)
    print('grad_input', grad_input)
    print('grad_output', grad_output)

In [ ]:
my_multiply = MyMultiply()

In [ ]:
my_multiply.register_full_backward_hook(backward_hook)

In [ ]:
c = my_multiply(a, b)
c.backward()

In [ ]:
from transformers import AutoTokenizer, AutoModelForMaskedLM

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('roberta-base')
model = AutoModelForMaskedLM.from_pretrained('roberta-base')

In [ ]:
sentence = "A pleasure to watch. <mask> <mask> great."

In [ ]:
token_ids = tokenizer.encode(sentence, return_tensors="pt")
token_ids

In [ ]:
masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().flatten()

In [ ]:
masked_position

In [ ]:
model(token_ids)

In [ ]:
with torch.no_grad():
    output = model(token_ids)

In [ ]:
output

In [ ]:
last_hidden_state = output[0].squeeze()

In [ ]:
last_hidden_state

In [ ]:
list_of_list = []
for index, mask_index in enumerate(masked_position):
    print(f"index: {index}, mask_index: {mask_index}")
    mask_hidden_state = last_hidden_state[mask_index]
    idx = torch.topk(mask_hidden_state, k = 5, dim=0)[1]
    print(f"idx: {idx}")
    words = [tokenizer.decode(x.item()).strip() for x in idx]
    list_of_list.append(words)
    print(f"Mask: {index+1}, Guesses: {words}")

In [ ]:
best_guess = ""
for j in list_of_list:
    best_guess = best_guess+" "+j[0]

In [ ]:
best_guess

In [ ]:
from datasets import load_dataset

In [ ]:
sst2 = load_dataset("glue","sst2")

In [ ]:
k_16_val = sst2['validation'][:16]

In [ ]:
k_16_val

In [2]:
input_ids = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
input_ids

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
trigger_token_pos = torch.tensor([[2],[1],[0]])

In [5]:
trigger_token_pos

tensor([[2],
        [1],
        [0]])

In [10]:
input_ids

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
input_ids = torch.tensor([1,2,3])

In [18]:
input_ids[1] = 9

In [33]:
input_ids

tensor([1, 9, 3])

In [41]:
import numpy as np
input_ids2 = np.array([4,5,6])
input_ids3 = np.array([1,2,3])

In [ ]:
encoding_list = []
encoding_list.append(input_ids2)
encoding_list.append(input_ids3)
np.array(encoding_list)

In [35]:
input_ids0 = torch.stack((input_ids, input_ids2), dim=0)

In [39]:
encoding_list = 

[array([1, 9, 3]), array([4, 5, 6])]

In [36]:
torch.stack((input_ids0, input_ids2), dim=0)

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [3] at entry 1

In [1]:
from transformers import AutoModelForMaskedLM

In [2]:
def backward_hook(module, grad_in, grad_out):
    print(f"grad_out: {grad_out}")

In [14]:
model_LM = AutoModelForMaskedLM.from_pretrained("roberta-base")
model_LM

RobertaForMaskedLM(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNor

In [15]:
from transformers import AutoModel

In [16]:
model = AutoModel.from_pretrained("roberta-base")

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.dense.bias', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [5]:
embeddings = model.roberta.embeddings.word_embeddings

In [6]:
embeddings.register_full_backward_hook(backward_hook)

In [8]:
import torch
from transformers import AutoTokenizer

In [9]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

In [12]:
text = "I love this film."
model_inputs = tokenizer.encode_plus(text)

In [19]:
loss = model(model_inputs["input_ids"], model_inputs["attention_masks"])

KeyError: 'attention_masks'

In [47]:
x = torch.randn(6, 3, 4)

In [48]:
x

tensor([[[ 0.7355,  0.7385,  0.3897,  0.3474],
         [-0.3760,  0.1875, -0.8486,  1.9865],
         [ 0.6533,  0.9322, -1.0370, -1.0321]],

        [[-0.5080,  0.9479, -0.7883,  0.7350],
         [-0.6821, -0.7658, -2.5501, -2.4049],
         [ 0.5876, -0.0761, -0.3878,  0.5497]],

        [[-0.9185, -0.9351,  0.1618, -1.0399],
         [ 0.1141, -0.0998,  0.2193, -0.0797],
         [ 0.5163, -1.3550,  0.5847, -0.6797]],

        [[-0.3077,  0.5037, -0.5051, -0.6428],
         [-0.2886, -2.3119,  0.4147,  0.0797],
         [-0.1951, -0.4515,  1.8489, -1.6408]],

        [[-0.1316, -0.3118,  0.3390,  1.8787],
         [-1.0587, -1.0375,  0.0529,  0.3393],
         [ 1.7818, -0.9404, -0.3334,  0.1080]],

        [[ 0.6194, -1.3400, -2.4347,  1.3792],
         [-0.2325,  0.2713,  0.5366,  1.0179],
         [-0.3320,  0.3746,  0.4161,  1.1477]]])

In [49]:
indices = torch.tensor([1, 0, 2, 1, 2, 0])

In [44]:
torch.gather(x, dim = 0, index = indices)

RuntimeError: Index tensor must have the same number of dimensions as input tensor

In [52]:
torch.arange(x.size(0))

tensor([0, 1, 2, 3, 4, 5])

In [51]:
x[torch.arange(x.size(0)), indices]

tensor([[-0.3760,  0.1875, -0.8486,  1.9865],
        [-0.5080,  0.9479, -0.7883,  0.7350],
        [ 0.5163, -1.3550,  0.5847, -0.6797],
        [-0.2886, -2.3119,  0.4147,  0.0797],
        [ 1.7818, -0.9404, -0.3334,  0.1080],
        [ 0.6194, -1.3400, -2.4347,  1.3792]])